[afc]
api_url = "http://localhost:8000"

[dut]
host = "192.168.1.1"
port = 22
username = "admin"
password = "admin"
retry_count = 3
retry_delay = 5
connect_timeout = 10
command_timeout = 30

[rf]
api_url = "http://localhost:9000"